services:
  - type: web
    name: clerky
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      npm install && npm install firebase-admin
      # Install Python and dependencies
      python3 -m pip install --user -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

