name: Extract Keywords

on:
  push:
    paths:
      - 'guidance/**'

jobs:
  extract_keywords:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim

    steps:
    - name: Install dependencies and Clone repository
      run: |
        apt-get update
        apt-get install -y git
        git clone https://github.com/<your-username>/<your-repo>.git /workspace
        cd /workspace
        pip install nltk
        pip freeze  # List installed Python packages for verification

    - name: Run keyword extraction script
      run: |
        cd /workspace
        python scripts/extract_keywords.py
