name: Extract Keywords

on:
  push:
    paths:
      - 'guidance/**'

jobs:
  extract_keywords:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        apt-get update
        apt-get install -y git
        pip install nltk
        pip freeze  # List installed Python packages for verification

    - name: Run keyword extraction script
      run: |
        python scripts/extract_keywords.py
