name: Extract Keywords

on:
  push:
    paths:
      - 'guidance/**'

jobs:
  extract_keywords:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      run: |
        apt-get update
        apt-get install -y python3.8 python3-pip
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install nltk

    - name: Run keyword extraction script
      run: python3.8 scripts/extract_keywords.py
