name: Extract Keywords

on:
  push:
    branches:
      - main

jobs:
  extract_keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-documentai google-auth

    - name: Write GCP credentials to file
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | tr -d '\r' > gcloud_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcloud_key.json

    - name: Run keyword extraction
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PROCESSOR_ID: ${{ secrets.GCP_PROCESSOR_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: gcloud_key.json
      run: |
        FILE_PATH=$(git log -1 --pretty=format: --name-only --diff-filter=A | grep '.pdf' | head -n 1)
        echo "Processing file: $FILE_PATH"
        python scripts/extract_keywords.py "$FILE_PATH"
