name: Extract Keywords

on:
  push:
    branches:
      - main

jobs:
  extract_keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-documentai google-auth

    - name: Run keyword extraction
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PROCESSOR_ID: ${{ secrets.GCP_PROCESSOR_ID }}
      run: |
        python extract_keywords.py path/to/your/pdf/document.pdf
