name: Extract Keywords

on:
  push:
    paths:
      - 'guidance/*'  # Adjust the path as necessary

jobs:
  extract-keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-documentai nltk

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: Configure gcloud
      run: |
        gcloud config set project filepicker-422722  # Replace with your actual project ID

    - name: Get added files
      id: get_added_files
      run: |
        echo "Added files:"
        git log -1 --pretty=format: --name-only --diff-filter=A

    - name: Extract keywords
      env:
        FILE_PATH: ${{ steps.get_added_files.outputs.files }}
      run: |
        FILE_PATH=$(git log -1 --pretty=format: --name-only --diff-filter=A | head -n 1)
        if [ -z "$FILE_PATH" ]; then
          echo "No file path provided"
          exit 1
        fi
        echo "Processing file: $FILE_PATH"
        FILE_PATH=$FILE_PATH python scripts/extract_keywords.py  # Make sure the path is correct
