name: Extract Keywords

on:
  push:
    branches:
      - main

jobs:
  extract_keywords:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-documentai google-auth 
        pip install --upgrade openai
        pip install --upgrade pypdf2 
        pip install tiktoken

    - name: Run keyword extraction
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PROCESSOR_ID: ${{ secrets.GCP_PROCESSOR_ID }}
        
      run: |
        python scripts/extract_keywords.py

    - name: Add and commit extracted text files
      run: |
        git config --global user.email "Clerky2024@gmail.com"
        git config --global user.name "Ian Nouvel"
        git add .
        git commit -m "Added extracted text files"
    
    - name: Push changes to repository
      run: |
        git push
