
name: Summarize PDFs

on:
  push:
    paths:
      - 'guidance/**'

jobs:
  summarize_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pypdf2
        pip install --upgrade openai
        pip install tiktoken
        pip install watchdog
        pip install requests

    - name: Run summarization script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        python scripts/summarise_guidance.py

    - name: Handle Git Conflicts
      run: |
        git fetch origin main
        git reset --hard origin/main
        git pull origin main

    - name: Add and commit generated summary files
      run: |
        git config --global user.email "Clerky2024@gmail.com"
        git config --global user.name "Ian Nouvel"
        git add clerky/guidance/summary/*
        git commit -m "Added summaries for new PDFs"

    - name: Push changes to repository
      run: |
        git push
