name: Update Guidelines List

on:
  push:
    paths:
      - 'guidance/**/*.pdf'

jobs:
  update-guideline-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: List current PDF files
      id: list_pdfs
      run: |
        # List all PDF files in the guidance folder and remove the 'guidance/' prefix
        find guidance -name "*.pdf" | sed 's|guidance/||' > all_pdfs.txt

    - name: Display current PDFs for debugging
      run: cat all_pdfs.txt

    - name: Compare PDF list and update guidelines file
      run: |
        # Create list_of_guidelines.txt if it does not exist
        if [ ! -f "guidance/list_of_guidelines.txt" ]; then
          touch "guidance/list_of_guidelines.txt"
        fi
        
        # Display current content of list_of_guidelines.txt
        cat guidance/list_of_guidelines.txt || echo "No existing guidelines."

        # Find new PDFs by comparing with existing list
        new_pdfs=$(comm -23 <(sort all_pdfs.txt) <(sort guidance/list_of_guidelines.txt))

        # If new PDFs are found, append them to list_of_guidelines.txt
        echo "$new_pdfs" >> guidance/list_of_guidelines.txt

    - name: Display updated guidelines list for debugging
      run: cat guidance/list_of_guidelines.txt

    - name: Commit and push changes
      if: success()
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add guidance/list_of_guidelines.txt all_pdfs.txt
        git commit -m "Update list of guidelines with new PDFs"
        git push
